#!/usr/bin/env bash
ARCHIVE="https://odooku.s3.amazonaws.com/heroku-22/runtimes/python-3.10.5.tar.gz"

if [ ! -f ".heroku/python/bin/python" ]; then
  puts-step "Bootstrapping python"
  mkdir -p .heroku/python
  curl -s $ARCHIVE 2> /dev/null | tar zxv -C .heroku/python &> /dev/null
fi
